### ISSUE TITLE
plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [shivareddyiirs/QRealTimeold#1]
Please remove .pyc files and create a folder to put the test data into.
![functionality](https://user-images.githubusercontent.com/2510900/31987659-c8febf50-b96c-11e7-8e00-2c68af479b6d.png)

**Comment by shivareddyiirs** [comment]
it already have removed .pyc files.
No data is required but I have one test folder where code to test the
plugin is given.

regards

Thanks & Regards
Shiva Reddy K.
Scientist/Engineer 'SC'
Indian Institute of Remote Sensing,
Indian Space Research Organisation
Department of Space
4-Kalidas Road
Dehradun
mobile: 8791806093

**Comment by shivareddyiirs** [comment]
Sorry for this mistake. 
The acutal repository for this pluign is updated in QGIS plugin repository. 
Below is the link to plugin repository
https://github.com/shivareddyiirs/QRealTimePlugin

**Comment by shivareddyiirs** [comment]
Please consider this plugin page instead(updated metadata also)

https://github.com/shivareddyiirs/QRealTimePlugin
